In [1]:
using StaticArrays

In [2]:
struct inputParms
    box::SVector{3, Float64}
    T::Float64
    β::Float64
    steps::Int
    optimizer::String
end

In [3]:
NA = 6.02214076E23 # [mol-1]
kB = 1.38064852E-23 * NA / 1000 # [kJ/(mol*K)];

In [4]:
fieldnames(inputParms)

(:box, :T, :β, :steps, :optimizer)

In [5]:
fieldtypes(inputParms)

(SVector{3, Float64}, Float64, Float64, Int64, String)

In [6]:
fields = [String(field) for field in fieldnames(inputParms)]

5-element Vector{String}:
 "box"
 "T"
 "β"
 "steps"
 "optimizer"

In [7]:
input = ["# Data", "", "T = 95", "optimizer = Momentum", "box = 36.405 36.405 36.405", "steps = 100"]

6-element Vector{String}:
 "# Data"
 ""
 "T = 95"
 "optimizer = Momentum"
 "box = 36.405 36.405 36.405"
 "steps = 100"

In [8]:
inputdata = [split(line) for line in input]

6-element Vector{Vector{SubString{String}}}:
 ["#", "Data"]
 []
 ["T", "=", "95"]
 ["optimizer", "=", "Momentum"]
 ["box", "=", "36.405", "36.405", "36.405"]
 ["steps", "=", "100"]

In [9]:
vars = []
for (field, fieldtype) in zip(fields, fieldtypes(inputParms))
    for inputvector in inputdata
        if length(inputvector) != 0 && field == inputvector[1]
            if field == "box"
                box = zeros(3)
                box[1] = parse(Float64, inputvector[3])
                box[2] = parse(Float64, inputvector[4])
                box[3] = parse(Float64, inputvector[5])
                append!(vars, [box])
                println("$(field) = $(box)")            
            elseif field == "T"
                T = parse(Float64, inputvector[3])
                β = 1/(kB * T)
                append!(vars, T)  
                append!(vars, β)
                println("T = $(T)")
                println("β = $(β)")
            else
                println("$(field) = $(inputvector[3])")
                if fieldtype != String
                    append!(vars, parse(fieldtype, inputvector[3]))
                else
                    append!(vars, [inputvector[3]])
                end
            end
        end
    end
end

box = [36.405, 36.405, 36.405]
T = 95.0
β = 1.266025230073036
steps = 100
optimizer = Momentum


In [10]:
parameters = inputParms(vars...)

inputParms([36.405, 36.405, 36.405], 95.0, 1.266025230073036, 100, "Momentum")

In [11]:
parameters.β

1.266025230073036

In [12]:
parameters.T

95.0

In [13]:
parameters.box

3-element SVector{3, Float64} with indices SOneTo(3):
 36.405
 36.405
 36.405

In [14]:
parameters.optimizer

"Momentum"

In [15]:
parameters.steps

100

In [31]:
a = [1, 2, 3, 4, 5]
b = [2, 2, 2, 2, 2];

In [32]:
a .*= b

5-element Vector{Int64}:
  2
  4
  6
  8
 10